INSERT INTO `addon_account` (`name`, `label`, `shared`) VALUES
('society_ambulance', 'Ambulance', 1),
('society_bell', 'bell', 1),
('society_benny', 'benny', 1),
('society_diner', 'diner', 1),
('society_ferme', 'ferme', 1),
('society_galaxy', 'galaxy', 1),
('society_hen', 'hen', 1),
('society_koi', 'koi', 1),
('society_lsfd', 'lsfd', 1),
('society_lspd', 'lspd', 1
('society_sheriff', 'sheriff', 1),
('society_taxi', 'taxi', 1),
('society_tps', 'tpm', 1),
('society_vigne', 'vigne', 1),
('society_xero', 'xero', 1),
('society_yellow', 'yellow', 1);

INSERT INTO `addon_account_data` (`id`, `account_name`, `money`, `owner`) VALUES
(10, 'society_ambulance', 0, NULL),
(11, 'society_sheriff', 0, NULL),
(12, 'society_bell', 0, NULL),
(13, 'society_galaxy', 0, NULL),
(14, 'society_koi', 0, NULL),
(17, 'society_vigne', 0, NULL),
(20, 'society_tps', 0, NULL),
(21, 'society_ferme', 0, NULL),
(22, 'society_benny', 0, NULL),
(23, 'society_taxi', 0, NULL),
(24, 'society_hen', 0, NULL),
(27, 'society_diner', 0, NULL),
(28, 'society_xero', 0, NULL),
(31, 'society_lsfd', 0, NULL),
(34, 'society_lspd', 0, NULL),
(35, 'society_yellow', 0, NULL);

INSERT INTO `addon_inventory` (`name`, `label`, `shared`) VALUES
('society_ambulance', 'Ambulance', 1),
('society_bell', 'bell', 1),
('society_benny', 'benny', 1),
('society_diner', 'diner', 1),
('society_ferme', 'ferme', 1),
('society_galaxy', 'galaxy', 1),
('society_hen', 'hen', 1),
('society_koi', 'koi', 1),
('society_lsfd', 'lsfd', 1),
('society_lspd', 'lspd', 1),
('society_sheriff', 'sheriff', 1),
('society_taxi', 'taxi', 1),
('society_tps', 'tps', 1),
('society_vigne', 'vigne', 1),
('society_xero', 'xero', 1),
('society_yellow', 'yellow', 1);

INSERT INTO `jobs` (`name`, `label`) VALUES
('ambulance', 'L.S.E.S', 0),
('bell', 'Cluckin Bell', 0),
('benny', 'Bennys', 0),
('diner', 'Diner', 0),
('ferme', 'La Bonne Miche', 0),
('galaxy', 'Galaxy Club', 0),
('hen', 'Hen house', 0),
('koi', 'Koi', 0),
('lsfd', 'L.S.F.D', 0),
('lspd', 'lspd', 0),
('sheriff', 'B.C.S.O', 0),
('taxi', 'LS Transit', 0),
('tps', 'Youtools', 0),
('vigne', 'Vignoble Remambussa', 0),
('xero', 'xero', 0),
('yellow', 'yellow', 0);

INSERT INTO `job_grades` (`job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`) VALUES
(2, 'ambulance', 0, 'ambulance', 'Ambulancier', 0, '', ''),
(3, 'ambulance', 1, 'ambulance', 'Interne', 0, '', ''),
(4, 'ambulance', 2, 'doctor', 'Medecin', 0, '', ''),
(5, 'ambulance', 3, 'chief_doctor', 'Medecin-chef', 0, '', ''),
(6, 'ambulance', 4, 'boss', 'Directeur', 0, '', ''),
(7, 'ambulance', 5, 'boss', 'co-Directeur', 0, '', ''),
(8, 'ambulance', 6, 'boss', 'Directeur', 0, '', ''),
(41, 'sheriff', 0, 'runner', 'recrue', 0, '', ''),
(42, 'sheriff', 1, 'deputy', 'Deputy I', 0, '', ''),
(43, 'sheriff', 2, 'deputy', 'Deputy II', 0, '', ''),
(44, 'sheriff', 3, 'deputy', 'Deputy Senior', 0, '', ''),
(45, 'sheriff', 4, 'sergeant', 'Sergent', 0, '', ''),
(46, 'sheriff', 5, 'lieutenant', 'Lieutenant', 0, '', ''),
(47, 'sheriff', 6, 'boss', 'Major', 0, '', ''),
(48, 'sheriff', 7, 'boss', 'Adjoint', 0, '', ''),
(49, 'sheriff', 8, 'boss', 'Commandant', 0, '', ''),
(50, 'bell', 0, 'runner', 'Esclave', 0, '', ''),
(51, 'bell', 1, 'server', 'Stagiaire', 0, '', ''),
(52, 'bell', 2, 'manager', 'Employé', 0, '', ''),
(54, 'bell', 4, 'boss', 'Patron', 0, '', ''),
(55, 'galaxy', 0, 'runner', 'sécurité', 0, '', ''),
(56, 'galaxy', 1, 'server', 'Danseuse', 0, '', ''),
(57, 'galaxy', 2, 'manager', 'Barman / Barmaid', 0, '', ''),
(58, 'galaxy', 3, 'boss', 'Co-Patron', 0, '', ''),
(59, 'galaxy', 4, 'boss', 'Patron', 0, '', ''),
(60, 'koi', 0, 'runner', 'Runner', 0, '', ''),
(61, 'koi', 1, 'server', 'Serveur', 0, '', ''),
(62, 'koi', 2, 'manager', 'Chef de salle', 0, '', ''),
(63, 'koi', 3, 'boss', 'Co-Patron', 0, '', ''),
(64, 'koi', 4, 'boss', 'Patron', 0, '', ''),
(75, 'vigne', 0, 'runner', 'Runner', 0, '', ''),
(76, 'vigne', 1, 'server', 'Serveur', 0, '', ''),
(77, 'vigne', 2, 'manager', 'Chef d\'équipe', 0, '', ''),
(78, 'vigne', 3, 'boss', 'Co-Patron', 0, '', ''),
(79, 'vigne', 4, 'boss', 'Patron', 0, '', ''),
(90, 'tps', 0, 'runner', 'Interimaire', 0, '', ''),
(91, 'tps', 1, 'server', 'Employé', 0, '', ''),
(92, 'tps', 2, 'manager', 'Chef d\'equipe', 0, '', ''),
(93, 'tps', 3, 'boss', 'Adjoint', 0, '', ''),
(94, 'tps', 4, 'boss', 'Directeur', 1000, '', ''),
(95, 'ferme', 0, 'runner', 'Stagiaire', 0, '', ''),
(96, 'ferme', 1, 'server', 'Employer', 0, '', ''),
(97, 'ferme', 2, 'manager', 'Chef d\'équipe', 0, '', ''),
(98, 'ferme', 3, 'boss', 'Co-Patron', 0, '', ''),
(99, 'ferme', 4, 'boss', 'Patron', 0, '', ''),
(100, 'benny', 0, 'runner', 'dépanneur ', 0, '', ''),
(101, 'benny', 1, 'server', 'mecanicien', 0, '', ''),
(102, 'benny', 2, 'manager', 'chef méca ou chef répa ', 0, '', ''),
(103, 'benny', 3, 'boss', 'responsable', 0, '', ''),
(104, 'benny', 4, 'boss', 'Patron', 0, '', ''),
(105, 'taxi', 0, 'runner', 'Stagiaire', 0, '', ''),
(106, 'taxi', 1, 'server', 'Chaufeur', 0, '', ''),
(107, 'taxi', 2, 'manager', 'D.R.H', 0, '', ''),
(108, 'taxi', 3, 'boss', 'Co-Patron', 0, '', ''),
(109, 'taxi', 4, 'boss', 'Patron', 0, '', ''),
(110, 'hen', 0, 'runner', 'Runner', 0, '', ''),
(111, 'hen', 1, 'server', 'Barman', 0, '', ''),
(112, 'hen', 2, 'manager', 'Agent Sécurité', 0, '', ''),
(113, 'hen', 3, 'boss', 'Co-Patron', 0, '', ''),
(114, 'hen', 4, 'boss', 'Patron', 0, '', ''),
(119, 'diner', 0, 'runner', 'Eoraptor', 0, '', ''),
(120, 'diner', 1, 'server', 'Aucasaure', 0, '', ''),
(121, 'diner', 2, 'manager', 'Cératosaure', 0, '', ''),
(122, 'diner', 3, 'boss', 'Gorgosaure', 0, '', ''),
(123, 'diner', 4, 'boss', 'Tyranosaure', 0, '', ''),
(124, 'xero', 0, 'runner', 'Stagiaire', 0, '', ''),
(125, 'xero', 1, 'server', 'Vendeur ', 0, '', ''),
(126, 'xero', 2, 'manager', 'Responsable', 0, '', ''),
(127, 'xero', 3, 'boss', 'Co-Patron', 0, '', ''),
(128, 'xero', 4, 'boss', 'Patron', 0, '', ''),
(137, 'lsfd', 0, 'recrue', 'Recrue', 0, '', ''),
(138, 'lsfd', 1, 'volontaire', 'Volontaire', 0, '', ''),
(139, 'lsfd', 2, '1class', '1er Classe', 0, '', ''),
(140, 'lsfd', 3, 'caporal1', 'Caporal I', 0, '', ''),
(141, 'lsfd', 4, 'caporal2', 'Caporal II', 0, '', ''),
(142, 'lsfd', 5, 'capichef', 'Caporal Chef', 0, '', ''),
(143, 'lsfd', 6, 'sergent1', 'Sergent I', 0, '', ''),
(144, 'lsfd', 7, 'sergent2', 'Sergent II', 0, '', ''),
(145, 'lsfd', 8, 'adjudant1', 'Adjudant I', 0, '', ''),
(146, 'lsfd', 9, 'adjudant2', 'Adjudant II', 0, '', ''),
(147, 'lsfd', 10, 'adjudantmajor', 'Adjudant Major', 0, '', ''),
(148, 'lsfd', 11, 'expert', 'Expert', 0, '', ''),
(149, 'lsfd', 12, 'aspirant', 'Aspirant', 0, '', ''),
(150, 'lsfd', 13, 'lieutenant', 'Lieutenant', 0, '', ''),
(151, 'lsfd', 14, 'commandant', 'Commandant', 0, '', ''),
(152, 'lsfd', 15, 'boss', 'Battalion - Chief', 0, '', ''),
(153, 'lsfd', 16, 'boss', 'Division - Chief', 0, '', ''),
(154, 'lsfd', 17, 'boss', 'Deputy - Chief', 0, '', ''),
(155, 'lsfd', 18, 'boss', 'Fire - Chief', 0, '', ''),
(163, 'lspd', 0, 'recrue', 'Recrue', 0, '', ''),
(164, 'lspd', 1, 'offi1', 'Officier I', 0, '', ''),
(165, 'lspd', 2, 'offi2', 'Officier II', 0, '', ''),
(166, 'lspd', 3, 'offi3', 'Officier III', 0, '', ''),
(167, 'lspd', 4, 'sergent1', 'Sergent I', 0, '', ''),
(168, 'lspd', 5, 'sergent2', 'Sergent II', 0, '', ''),
(169, 'lspd', 6, 'detective', 'Detective', 0, '', ''),
(170, 'lspd', 7, 'lieutenant1', 'Lieutenant I', 0, '', ''),
(171, 'lspd', 8, 'boss', 'Lieutenant II', 0, '', ''),
(172, 'lspd', 9, 'boss', 'Capitaine', 0, '', ''),
(173, 'lspd', 10, 'boss', 'Commandant', 0, '', ''),
(174, 'yellow', 0, 'recrue', 'Barman', 0, '', ''),
(175, 'yellow', 1, 'offi1', 'Chef barman', 0, '', ''),
(176, 'yellow', 2, 'boss', 'Manager', 0, '', ''),
(177, 'yellow', 3, 'boss', 'Co patron', 0, '', ''),
(178, 'yellow', 4, 'boss', 'Patron', 0, '', '');
